# Generated by Django 4.2 on 2023-05-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozecafe', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(),
        ),
    ]
