# Generated by Django 4.2 on 2023-05-08 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozecafe', '0005_alter_order_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2023, 5, 8, 16, 1, 23, 217135))),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
